[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit BNO08x @ ^1.2.5
  adafruit/Adafruit BusIO @ ^1.14.0
  paulstoffregen/Encoder @ ^1.4.4
  bblanchon/ArduinoJson @ ^7